changelog:
  categories:
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - chore
        - dependencies
